import { StoreProvider } from "@/store/StoreProvider";
import 'simplebar-react/dist/simplebar.min.css';
import 'react-toastify/dist/ReactToastify.css';
import "flatpickr/dist/themes/light.css";
import "react-svg-map/lib/index.css";
// import ToastifyContainer from "@/components/toastify/ToastifyContainer";
import localFont from 'next/font/local'
import './globals.css'


const PlusJakartaSans = localFont({
  src: '../../public/fonts/PlusJakartaSans-Medium.ttf',
  weight: '400',
  style: 'normal',
  display: 'swap',
  variable: '--font-PlusJakartaSans',
})
export const metadata = {
  title: "MED Intell Medical project",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {

  return (
    <html lang="en" dir="ltr" suppressHydrationWarning  >
      <body
        className={`${PlusJakartaSans.variable} antialiased`}
      >
        {/* <Landing/> */}
        <StoreProvider>
          {/* <protectRoute></protectRoute> */}
          {/* <Layout> */}
          {children}
          {/* </Layout> */}
        </StoreProvider>
        {/* <ToastifyContainer /> */}
      </body>
    </html>
  );
}
